name: bikurimen

on:
  workflow_dispatch:

jobs:
  build:
    name: Memulai Mesin...
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: Mengunduh n Memasang Esensial
        run: |
          Invoke-WebRequest -Uri "https://github.com/yongskru/machine/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Sudah siap
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
